require("imats.plugins-setup")
require("imats.core.options")
require("imats.core.keymaps")
require("imats.core.colorscheme")

-- plugin imports
require("imats.plugins.lsp.mason-config")
require("imats.plugins.lsp.lspsaga")
require("imats.plugins.lsp.lspconfig")
require("imats.plugins.lsp.null-ls")
require("imats.plugins.comment")
require("imats.plugins.nvim-tree")
require("imats.plugins.lualine")
require("imats.plugins.telescope")
require("imats.plugins.nvim-cmp")
require("imats.plugins.autopairs")
require("imats.plugins.treesitter")
require("imats.plugins.gitsigns")
